spring.application.name=trainer-system

server.servlet.context-path=/trainer-system/api

#PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/trainer_db
spring.datasource.username=fabiana
spring.datasource.password=fabiana.platzi
spring.jpa.properties.hibernate.jdbc.time_zone=America/Argentina/Buenos_Aires
